name: Publish Nightly Docker Image
on:
  push:
    paths-ignore:
      - '.github/*.yml'
      - '*.md'
      - '*.yml'
      - '.rubocop.yml'
      - 'Rakefile'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: build gem
      run: |
        bundle install
        bundle exec rake build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to Github Registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          REPLACE_CHINA_MIRROR=false
        tags: icyleaf/app_status_notification:nightly
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
